-- Tabla para registros con QR
CREATE TABLE IF NOT EXISTS registro_qr (
  id bigint generated by default as identity primary key,
  nombre text,
  correo text,
  departamento text,
  hora_entrada time,
  hora_salida time,
  qr_id text,
  fecha date,
  tipo text
);

-- Tabla para registro de visitantes
CREATE TABLE IF NOT EXISTS registro_visitantes (
  id bigint generated by default as identity primary key,
  nombre text,
  correo text,
  fecha_nac date,
  domicilio text,
  telefono text,
  departamento text,
  hora_entrada time,
  hora_salida time,
  qr_id text,
  tipo text
);

-- Tabla para accesos (histórico de entradas)
CREATE TABLE IF NOT EXISTS accesos (
  id bigint generated by default as identity primary key,
  nombre text,
  correo text,
  departamento text,
  fecha date,
  hora text,
  qr_id text,
  tipo text
);

