-- ================================
-- TABLA registro_qr
-- ================================
CREATE TABLE IF NOT EXISTS registro_qr (
  id bigint generated by default as identity primary key,
  nombre text,
  correo text,
  departamento text,
  hora_entrada time,
  hora_salida time,
  qr_id text,
  fecha date,
  tipo text
);

-- Insert de prueba en registro_qr
INSERT INTO registro_qr (nombre, correo, departamento, hora_entrada, hora_salida, qr_id, fecha, tipo)
VALUES 
('Juan Pérez', 'juan@example.com', 'Oficina del Secretario', '09:00', '11:00', 'qr123abc', '2025-08-26', 'registro_qr'),
('María López', 'maria@example.com', 'Dirección de Emprendimiento', '10:00', '12:00', 'qr456def', '2025-08-26', 'registro_qr');

-- ================================
-- TABLA registro_visitantes
-- ================================
CREATE TABLE IF NOT EXISTS registro_visitantes (
  id bigint generated by default as identity primary key,
  nombre text,
  correo text,
  fecha_nac date,
  domicilio text,
  telefono text,
  departamento text,
  hora_entrada time,
  hora_salida time,
  qr_id text,
  tipo text
);

-- Insert de prueba en registro_visitantes
INSERT INTO registro_visitantes (nombre, correo, fecha_nac, domicilio, telefono, departamento, hora_entrada, hora_salida, qr_id, tipo)
VALUES 
('Carlos Ramírez', 'carlos@example.com', '1990-05-12', 'Av. Reforma 123', '5551234567', 'Fomento al Empleo', '08:30', '09:30', 'qr789ghi', 'registro_visitantes');

-- ================================
-- TABLA accesos
-- ================================
CREATE TABLE IF NOT EXISTS accesos (
  id bigint generated by default as identity primary key,
  nombre text,
  correo text,
  departamento text,
  fecha date,
  hora text,
  qr_id text,
  tipo text
);

-- Insert de prueba en accesos
INSERT INTO accesos (nombre, correo, departamento, fecha, hora, qr_id, tipo)
VALUES 
('Juan Pérez', 'juan@example.com', 'Oficina del Secretario', '2025-08-26', '09:15', 'qr123abc', 'acceso');
