CREATE TABLE IF NOT EXISTS registro_qr (
  id bigint generated by default as identity primary key,
  nombre text,
  correo text,
  departamento text,
  hora_entrada time,
  hora_salida time,
  qr_id text
);

CREATE TABLE IF NOT EXISTS registro_visitantes (
  id bigint generated by default as identity primary key,
  nombre text,
  correo text,
  fecha_nac date,
  domicilio text,
  telefono text,
  departamento text,
  hora_entrada time,
  hora_salida time,
  qr_id text
);
